### PR TITLE
Config appearance

### PR DESCRIPTION
**Pull request by zelfroster**
Added feature to set font-size persistently in browser using [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage).

Now, user can set a font-size according to their screen sizes.
Also, fixed some UI issues while implementing this feature.
image

### CODE REVIEW

**Comment by rottencandy** [comment]
Does this PR include commits from other PRs also?

**Comment by rottencandy** [comment]
Is there a real need for this feature? Won't users simply use the font size setting in their browsers?

**Comment by zelfroster** [comment]
> Is there a real need for this feature? Won't users simply use the font size setting in their browsers?

Yeah, but I thought since sometimes on smaller screens the UI becomes large to view everything perfectly. I know they can control the zoom level with `Ctrl`+`+` `Ctrl`+`-` to adjust that. But I thought maybe giving them an option to set it themselves would be a good option.

**Comment by rottencandy** [comment]
We can have this but I was pointing that all browsers also support setting custom font sizes & types if users like. That's why features like this are not commonly seen in web apps.

screenshot-1688366702

**Comment by rottencandy** [comment]
Like in this PR you have 5 size options, what if users want sizes beyond that, a setting like this is best handled by the browser itself in my opinion

**Comment by zelfroster** [comment]
> Like in this PR you have 5 size options, what if users want sizes beyond that, a setting like this is best handled by the browser itself in my opinion

Ahh, got it. So, I guess I can close this PR now. 👍🏼

**Pull request closed without merging**
