### PR TITLE
boards page

### PR DESCRIPTION
**Pull request by defnax**
Added page for testing the boards api.
its more cloned from channels thx to @Sukhamjot-Singh
it does not work like how i expected im not javscript expert, its unstable

View the BoardView not working not sure why, maybe has todo with the unfinished boards api

image

### CODE REVIEW

**Comment by Sukhamjot-Singh** [comment]
I can see that the boards are being displayed atleast.
I will look into what errors that are coming maybe tomorrow. Because a channel has posts and other things, maybe some of the API's are different.

**Comment by defnax** [comment]
hi not importend yet only created a page maybe makes your life better when a page is there :)
some apis are missed for boards i think cyril working on it example: this one
maybe needed:
subscribeToBoard
createBoardV2
createCommentV2
createPostV2
createVoteV2

Boards has voting for posts -> voteForPost

**Comment by defnax** [comment]
hi get this error  

> Failed to load resource: the server responded with a status of 401 (Unauthorized)
app.js:7595 login [generic] No error
app.js:7528 loading 686 users ...
app.js:7517 unhandled event Object
app.js:7517 unhandled event Object
app.js:7517 unhandled event Object
app.js:7517 unhandled event Object
app.js:7517 unhandled event Object
app.js:7517 unhandled event Object
**app.js:5861 TypeError: Cannot read properties of undefined (reading 'mData')**
    at Object.view (app.js:189:52)
    at Function.callHook (app.js:4814:21)
    at initComponent (app.js:4957:50)
    at createComponent (app.js:4963:7)
    at createNode (app.js:4855:14)
    at updateNode (app.js:5246:9)
    at updateNodes (app.js:5101:18)
    at updateElement (app.js:5303:11)
    at updateNode (app.js:5241:15)
    at updateNodes (app.js:5101:18)

**Comment by Sukhamjot-Singh** [comment]
I don't think [getBoardsSummaries ](https://github.com/RetroShare/libretroshare/blob/72f8b7e8e240923731a141c6f2a0438588f04f59/src/retroshare/rsposted.h#L158) is working alright. 
It returns nothing on 
`curl -u login:password http://localhost:9092/rsposted/getBoardsSummaries`

**Comment by Sukhamjot-Singh** [comment]
image
This is what I get when this PR calls for getBoardsSummaries.
Channels and forum summaries are working fine.

**Comment by defnax** [comment]
> image This is what I get when this PR calls for getBoardsSummaries. Channels and forum summaries are working fine.

it worked, but im not yet tested with master

**Comment by csoler** [comment]
The method for channels and boards are exactly the same. That's surprising.

**Comment by Sukhamjot-Singh** [comment]
Maybe there is a problem on my end.

`curl -u  login:password http://localhost:9092/rsgxschannels/getChannelsSummaries` 
This works.

`curl -u login:password http://localhost:9092/rsposted/getBoardsSummaries`
This doesn't.

**Comment by Sukhamjot-Singh** [comment]
For updating Retroshare, does this work?
image

Not really aware of this linux flow.

**Comment by csoler** [comment]
no! It updates the released version, not the current master

**Comment by Sukhamjot-Singh** [comment]
> 

Well how can I update the current master? I have not once updated it.

**Comment by defnax** [comment]
im not sure if the getContentSummaries is importend to retrieve the image data
Channels has always that

```
async function updateDisplayBoards(keyid, details) {
  const res1 = await rs.rsJsonApiRequest('/rsPosted/getBoardsInfo', {
    boardsIds: [keyid],
  });
  details = res1.body.boardsInfo[0];
  Data.DisplayBoards[keyid] = {
    name: details.mMeta.mGroupName,
    isSearched: true,
    description: details.mDescription,
    image: details.mImage,
    author: details.mMeta.mAuthorId,
    isSubscribed:
      details.mMeta.mSubscribeFlags === GROUP_SUBSCRIBE_SUBSCRIBED ||
      details.mMeta.mSubscribeFlags === GROUP_MY_BOARD,
    posts: details.mMeta.mVisibleMsgCount,
    activity: details.mMeta.mLastPost,
    created: details.mMeta.mPublishTs,
    all: details,
  };

  if (Data.Posts[keyid] === undefined) {
    Data.Posts[keyid] = {};
  }

  /*const res2 = await rs.rsJsonApiRequest('/rsPosted/getContentSummaries', {
    boardId: keyid,
  });

  if (res2.body.retval) {
    res2.body.summaries.map((content) => {
      updateContent(content, keyid);
    });
  }*/
 
}
```

**Comment by Sukhamjot-Singh** [comment]
> 

I am not sure I get you. We are getting the image from the BoardsInfo API. The contentSummaries is for the posts and other thing.

**Comment by defnax** [comment]
> > 
> 
> I am not sure I get you. We are getting the image from the BoardsInfo API. The contentSummaries is for the posts and other thing.

thank you, you get updated your retroshare to master?

**Comment by Sukhamjot-Singh** [comment]
> > > 
> > 
> > 
> > I am not sure I get you. We are getting the image from the BoardsInfo API. The contentSummaries is for the posts and other thing.
> 
> thank you, you get updated your retroshare to master?

Yes.

**Comment by defnax** [comment]
Hi, you can look why image doesnt get loaded?

**Comment by Sukhamjot-Singh** [comment]
> Hi, you can look why image doesnt get loaded?

I started a review suggesting changes.

image: details.mGroupImage for line 55

**Comment by defnax** [comment]
@csoler can you merge this

**Pull request merged**
