### PR TITLE
Fix build webui on macos platfrom

### PR DESCRIPTION
**Pull request by defnax**

### CODE REVIEW

**Comment by defnax** [comment]
@thunder2 
on macos go dir up with `/../../webui-src `does not work

**Comment by thunder2** [comment]
This dosn't work winth MSYS2 and maybe with linux too.
$(readlink -f $(dirname $0)) has no trailing slash
The result is now "<some path>/retroshare-webui/webui-src/make-src../../webui" but  "<some path>/retroshare-webui/webui-src/make-src/../../webui" (slash before ..) is needed

**Comment by defnax** [comment]
but on macos compile it gets issue to buld webui, i need to edit manually the build.sh.
for macos there can be used if def or something?
the cmake compile uses the build.sh and then i get the first error there with the path

**Comment by thunder2** [comment]
Can you check the result of $(readlink -f $(dirname $0)). On MSYS2 and linux its the current directory.
Change the script like this

#!/bin/bash

# create webfiles from sources at compile time (works without npm/node.js)

echo "### Starting WebUI build ###"

echo "---"
echo $(readlink -f $(dirname $0))
echo "---"
exit 1

src=$(readlink -f $(dirname $0))../../webui-src

**Comment by defnax** [comment]
> Can you check the result of `$(readlink -f $(dirname $0))`. On MSYS2 and linux its the current directory. Change the script like this
> 
> ```
> #!/bin/bash
> 
> # create webfiles from sources at compile time (works without npm/node.js)
> 
> echo "### Starting WebUI build ###"
> 
> echo "---"
> echo $(readlink -f $(dirname $0))
> echo "---"
> exit 1
> 
> src=$(readlink -f $(dirname $0))../../webui-src
> ```

thx i will test tonight

**Comment by defnax** [comment]
i get this

Untitled 2

**Comment by thunder2** [comment]
The ```readlink -f``` doesn't work on your macOS version. On stackoverflow I read, that it is supported on macOS 12.3.

**Comment by defnax** [comment]
> The `readlink -f` doesn't work on your macOS version. On stackoverflow I read, that it is supported on macOS 12.3.
ah ok,.i has macos 10.13 and 10.15 (VM)
theni i can live with it, now most people have newer macos versions

**Pull request closed without merging**
