### PR TITLE
try to fix eslint and prettier issues

### PR DESCRIPTION
**Pull request by zeners**
eslint errors fixed, 8 warnings outstanding

eslint and prettier config are incompatible

### CODE REVIEW

**Review by rottencandy — COMMENTED** [review]
Thanks. Looks mostly fine overall.

Since we're not using the `.scss` files anymore, I'm wondering if it would be good to delete them, they won't work without the sass compiler anyways.

Also the 7 warnings seem to be pretty simple usage before define cases, would be great if you could fix them too.

**Comment by zeners** [comment]
How about the clashing defines between eslint and prettier? Currently you only can fit one of the two. see https://github.com/RetroShare/RSNewWebUI/pull/32/commits/6c6c4528b60b77d4f55509fb4caf9d41b316bd6a

**Comment by rottencandy** [comment]
Hmm, apparently this is a known issue. The solution seems to be to check for indentation using only one of the tools.
I think we should remove the "indent" rule in eslint config, and let prettier handle the indentations.

**Comment by zeners** [comment]
how to change?

**Comment by rottencandy** [comment]
Just remove the indent rule from the config:
```diff
M webui-src/.eslintrc.json
@@ -17,10 +17,6 @@
     },
     "ignorePatterns": ["mithril.js", "assets/*", "make-src/*"],
     "rules": {
-        "indent": [
-            "error",
-            2
-        ],
         "linebreak-style": [
             "error",
             "unix"
```
It seems to work fine after this.

**Comment by zeners** [comment]
> Since we're not using the `.scss` files anymore, I'm wondering if it would be good to delete them, they won't work without the sass compiler anyways.

unsure: debugging features with npm background task in previous version was impressive.

**Comment by zeners** [comment]
all warnings and errors resolved

**Comment by rottencandy** [comment]
> unsure: debugging features with npm background task in previous version was impressive.

Not sure if I understand. By previous version, you mean the old webui? Because I don't think we ever used the scss and sass files in the new webui.

**Review by rottencandy — APPROVED** [review]
Everything else looks good. Thanks!

**Comment by zeners** [comment]
> By previous version, you mean the old webui? Because I don't think we ever used the scss and sass files in the new webui.

yes, the old webui. Where was a background-process that build the app-files from the source files on source-file change. The browser then referred the origin files and line-numbers and reflected instant that file changes without page reloading (don't know how it exactly works). 
I replaced that process for the build-process with the now available scripts to reduce build dependencies. It was never intended to remove that feature for development :)

**Comment by rottencandy** [comment]
I agree, hot code reloading with file watcher would be really nice to have. I don't know if there is any way of doing that without using node.

**Pull request merged**
