### PR TITLE
 RetroShare home Tab  UI improvement  and  added logic code for some functionality 

### PR DESCRIPTION
**Pull request by Kumaravinash9**
#35 
**please review this PR @rottencandy** 

UIcheck

## Copy retroID
image

## Open Help WebUI PopUp
openWebuiPopUp

## Add Friend popup
addFriend

### CODE REVIEW

**Comment by defnax** [comment]
but share button is not functional yet?
feature where i can copy cert format too to clipboard or enable to view optionaly the cert.

**Comment by Kumaravinash9** [comment]
> but the share button is not functional yet?
> feature where I can copy cert format too to the clipboard or enable to view optionally the cert.

Sending mail functionality is not implemented yet that's why I did not add these functionalities once sending mail feature implemented I will add the share option feature.

**Comment by rottencandy** [comment]
What if we use the logo itself, instead of creating it again using css?
https://github.com/RetroShare/RetroShare/blob/master/retroshare-gui/src/gui/images/logo/logo_web_nobackground.svg

**Comment by Kumaravinash9** [comment]
> What if we use the logo itself, instead of creating it again using css?
> https://github.com/RetroShare/RetroShare/blob/master/retroshare-gui/src/gui/images/logo/logo_web_nobackground.svg

Actually I didn't know about the image that's why I added css , html . Thank you @rottencandy I will add the image now

**Comment by defnax** [comment]
But you forget add a option to show the old cert format (optional), or option to can copy own cert to clipboard

**Comment by Kumaravinash9** [comment]
sorry @defnax for the late reply, Actually I planned to add all the features together. That'why i didnot add it

**Comment by defnax** [comment]
can this be merged? to have a master with up to date

**Comment by defnax** [comment]
@rottencandy @csoler

**Comment by Kumaravinash9** [comment]
Once i am done with the retroshare_mobile i will add the more feature into webUI.

**Pull request merged**
