### PR TITLE
feat: implement file search using js proxy

### LINKED ISSUE #73: File Search : Response from the `turtleSearchRequest` is not correctly formatted
The response from the `turtleSearchRequest` is not correctly formatted as JSON, so that's why `handleDeserialize` throws error when parsing in `rswebui.js`.
1682775057_Apr29_19:00:57

So, The correct format for response should be like this.
An object which will have its first item as a `retval: <boolean>`. And the second item which will be an array of all the result files `"results": [{},{}]`
```json
{
  "retval": true,
  "results": [{ "fSize": {}, "fHash": "", "fName": "", "fWeight": 0.0, "fSnippet": ""}, { }, { }]
}
```

The real response might look something like [this](https://pastebin.com/HWZeeg8B). 

And after formatting, It will look something like this.
1682785511_Apr29_21:55:11

### PR DESCRIPTION
**Pull request by zelfroster**
Closes #73 
Implemented File Search, which was pending from a long time.

Search results are shown in individual tabs for each search initiated, which is something like this.
file_search

This is not perfect enough, but usable. Need to do a lot of formatting and making its functionality better.
This PR needs a lot of improvement, please suggest anything which can make it better.

### CODE REVIEW

**Comment by csoler** [comment]
When I click on "submit" it takes me back to login screen. Anyone else experiencing the same problem?

**Comment by zelfroster** [comment]
> When I click on "submit" it takes me back to login screen. Anyone else experiencing the same problem?

I have cloned it from this branch and ran `qmake` again, and it works.
Clone this specific branch and then build it again.
```
git clone -b implement-file-search https://github.com/zelfroster/RSNewWebUI.git
```

It should work 😅

**Comment by csoler** [comment]
I'm recompiling libretroshare.  Missing recompilation may be the source of the problem.

**Comment by zelfroster** [comment]
> I'm recompiling libretroshare. Missing recompilation may be the source of the problem.

Ohh, yeah, when I started developing the first time, It was also the same.

**Comment by zelfroster** [comment]
> > I'm recompiling libretroshare. Missing recompilation may be the source of the problem.
> 
> Ohh, yeah, when I started developing this feature for the first time after you fixed libretroshare, It was also the same.

**Comment by csoler** [comment]
after recompiling, I get the same error. When it happens, the following message appears in retroshare-service console: "W 1684784770.356 JsonApiServer authentication handler blocked an attempt to call JSON API authenticated method: /rsEvents/registerEventsHandler user: webui error: 2006 Wrong API password category: RetroShare JSON API"
Do you follow the correct procedure for authenticated calls to json API ?

**Comment by zelfroster** [comment]
> it seems to work. I indeed made a mistake compiling. Possible improvements are: adding "download" buttons on the right side of each file (or anything that would allow to start a file transfer), file size and possibly hash. The information is all available in the search result.

Ohh, that's great. I was kinda scared.
Sure, will do it today itself, will make a table layout for it.

**Comment by zelfroster** [comment]
Made Layout for table and removed some unnecessary logs from console.

Currently, it looks like this
1684864471_May23_23:24:31

**Comment by zelfroster** [comment]
Fixed it so that search keyword page is show and results start to show as soon as they are received.
file_search_fixed

**Comment by zelfroster** [comment]
Now the latest searched keyword will be at the top and its results will be shown.

**Pull request merged**
