### PR TITLE
Improve sidebar UI

### LINKED ISSUE #62: Improve Sidebar UI
I am thinking of making the sidebar a bit modern.

So, I just wanted to ask, 

Is it Okay if I tweak the color scheme a bit? Or Should I go with the existing ones.

### PR DESCRIPTION
**Pull request by zelfroster**
Sidebar now has a modern look. 
Closes #62 
Suggest changes if any :)

1678440739_Mar10_15:02:19

### CODE REVIEW

**Comment by defnax** [comment]
wow looks better

**Comment by zelfroster** [comment]
> you have time to finish the webui?

I mean what exactly are you talking about. Pardon me 😅

**Comment by defnax** [comment]
> > you have time to finish the webui?
> 
> I mean what exactly are you talking about. Pardon me 😅

example the last webui dev wanted finish the mail system you cant use yet mails on webui (compose,reply,lots of things composer design...
boards page not done

**Comment by zelfroster** [comment]
> > > you have time to finish the webui?
> > 
> > 
> > I mean what exactly are you talking about. Pardon me sweat_smile
> 
> example the last webui dev wanted finish the mail system you cant use yet mails on webui (compose,reply,lots of things composer design... boards page not done

OK got it. So, just tell me where should I start first? I mean which section first.

**Comment by zelfroster** [comment]
> > > you have time to finish the webui?
> > 
> > 
> > I mean what exactly are you talking about. Pardon me sweat_smile
> 
> example the last webui dev wanted finish the mail system you cant use yet mails on webui (compose,reply,lots of things composer design... boards page not done

I am currently trying to improve the ui section by section, working on Network section now.

**Comment by defnax** [comment]
> > > > you have time to finish the webui?
> > > 
> > > 
> > > I mean what exactly are you talking about. Pardon me sweat_smile
> > 
> > 
> > example the last webui dev wanted finish the mail system you cant use yet mails on webui (compose,reply,lots of things composer design... boards page not done
> 
> I am currently trying to improve the ui section by section, working on Network section now.

thats realy great, with this help

**Comment by defnax** [comment]
yes i mentioed network page has a bad design to much big not useable,
https://github.com/RetroShare/RSNewWebUI/issues/36

**Comment by zelfroster** [comment]
Then Please, merge this PR, so I can work on other sections accordingly.

And one more thing, When should I start writing Proposal for GSOC.

**Comment by defnax** [comment]
> Then Please, merge this PR, so I can work on other sections accordingly.
> 
> And one more thing, When should I start writing Proposal for GSOC.

need to wait for @csoler he has the merge rights

**Comment by csoler** [comment]
Please keep in mind that the priority is to get things to work. Refactoring the whole UI is a lesser priority. Of course, that can be done once you reach a usable set of features in the UI.
However, I agree with you defnax on your report of  what doesn't work.
File search for instance is a really missing feature, but it's hard to do apparently.

**Comment by zelfroster** [comment]
> Please keep in mind that the priority is to get things to work. Refactoring the whole UI is a lesser priority. Of course, that can be done once you reach a usable set of features in the UI. However, I agree with you defnax on your report of what doesn't work. File search for instance is a really missing feature, but it's hard to do apparently.

Ok, So, It was File Search that needed to be done.
I was wondering which search is not working.

Also, How to upload files in RS? so that I can start working on it.

**Comment by defnax** [comment]
yes first priority is 100% working webui which is useable.
After done a better redesign and userfriendly all.
But mail system example is not useable yet, like how in rs qt ui :)

**Pull request merged**
