### PR TITLE
added libwebui.so* in .gitignore file

### PR DESCRIPTION
**Pull request by Kumaravinash9**
added libwebui.so*  in .gitignore. So none will push these file again

### CODE REVIEW

**Comment by Kumaravinash9** [comment]
> Do these files get generated for you on every build? Wondering if this is some qmake version issue. Because these files never get generated on my system.

No, I am not getting these on every build.

**Comment by Kumaravinash9** [comment]
It might be a problem with the qt version. I think we should add this `libwebui.so*` inside  `.gitignore` file until the qt version bug resolve.

**Comment by csoler** [comment]
Sorry to ask, but I'm surprised that you need a "libwebui.so" here. There's no pre-compiled parts in the webui as far as I know.

**Comment by rottencandy** [comment]
Wondering the same, I've never seen this when building. I don't see where the library files are coming from.

**Comment by Kumaravinash9** [comment]
I am also not getting `libwebui.so*` files whenever I build webui.  But gunjan pushed the libwebui.so* file in its PR.

**Comment by Kumaravinash9** [comment]
I think we should ask her about which OS and qt version she is using. This may be a problem with its OS or QT version.

**Comment by csoler** [comment]
these libwebui.so come from the action of "make" since qmake sees the "TEMPLATE=lib" statement in the .pro. The .so you get by typing make contains nothing, since it links nothing, and "make" shouldn't be used at all. Maybe there's a way to prevent Qt from generating anything when calling make. Using "TEMPLATE=app" seems to do the trick.

**Comment by rottencandy** [comment]
@Kumaravinash9 we won't be needing the gitignore entry anymore.

**Comment by Kumaravinash9** [comment]
> @Kumaravinash9 we won't be needing the gitignore entry anymore.

sorry, I forgot to remove `libwebui.so*` from .gitignore.

**Comment by Kumaravinash9** [comment]
> @Kumaravinash9 we won't be needing the gitignore entry anymore.

updated

**Review by rottencandy — APPROVED** [review]
Thanks, this works as expected.

**Pull request merged**
